server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-usuarios
              uri: lb://ms-usuarios
              predicates:
                - Path=/api/usuarios/**
            - id: ms-academico
              uri: lb://ms-academico
              predicates:
                - Path=/api/academico/**
            - id: ms-matricula
              uri: lb://ms-matricula
              predicates:
                - Path=/api/matricula/**
            - id: ms-libro-digital
              uri: lb://ms-libro-digital
              predicates:
                - Path=/api/libro/**
            - id: ms-comunicaciones
              uri: lb://ms-comunicaciones
              predicates:
                - Path=/api/comunicaciones/**
            - id: ms-reportes
              uri: lb://ms-reportes
              predicates:
                - Path=/api/reportes/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ENTRA_ISSUER_URI:https://login.microsoftonline.com/1148f910-11c6-41a3-94d3-dedca0cefa9c/v2.0}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

app:
  jwt:
    audience: ${ENTRA_API_CLIENT_ID:3ac3ede1-1d05-42df-8248-3fbde4240a87}
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:5173}