server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-usuarios
              uri: http://localhost:8081
              predicates:
                - Path=/api/usuarios/**
            - id: ms-academico
              uri: http://localhost:8082
              predicates:
                - Path=/api/academico/**
            - id: ms-matricula
              uri: http://localhost:8083
              predicates:
                - Path=/api/matricula/**
            - id: ms-libro-digital
              uri: http://localhost:8084
              predicates:
                - Path=/api/libro/**
            - id: ms-comunicaciones
              uri: http://localhost:8085
              predicates:
                - Path=/api/comunicaciones/**
            - id: ms-reportes
              uri: http://localhost:8086
              predicates:
                - Path=/api/reportes/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/1148f910-11c6-41a3-94d3-dedca0cefa9c/v2.0

eureka:
  client:
    enabled: false

app:
  jwt:
    secret: "c3VwZXJTZWNyZXRLZXlGb3JKS1RUZXN0aW5nS2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTA="
